In [6]:
import pandas as pd
import numpy as np

In [7]:
customer_df = pd.read_csv("../data/raw/customer_master.csv")
inventory_df = pd.read_csv("../data/raw/inventory_snapshot.csv")
promotions_df = pd.read_csv("../data/raw/promotions.csv")
sales_df = pd.read_csv("../data/raw/sales_transactions.csv")
sku_flags_df = pd.read_csv("../data/raw/sku_inventory_flags.csv")
sku_df = pd.read_csv("../data/raw/sku_master.csv")
store_df = pd.read_csv("../data/raw/store_master.csv")

In [8]:
print("Customer Dataset:", customer_df.shape)
print("Inventory Dataset:", inventory_df.shape)
print("Promotions Dataset:", promotions_df.shape)
print("Sales Dataset:", sales_df.shape)
print("SKU Inventory Flags Dataset:", sku_flags_df.shape)
print("SKU Master Dataset:", sku_df.shape)
print("Store Dataset:", store_df.shape)

Customer Dataset: (10000, 7)
Inventory Dataset: (26408, 6)
Promotions Dataset: (100, 8)
Sales Dataset: (9945511, 11)
SKU Inventory Flags Dataset: (600, 6)
SKU Master Dataset: (5000, 7)
Store Dataset: (30, 5)

In [9]:
print("=" * 60)
print("CUSTOMER DATASET")
display(customer_df.head())

print("=" * 60)
print("INVENTORY DATASET")
display(inventory_df.head())

print("=" * 60)
print("PROMOTIONS DATASET")
display(promotions_df.head())

print("=" * 60)
print("SALES DATASET")
display(sales_df.head())

print("=" * 60)
print("SKU INVENTORY FLAGS DATASET")
display(sku_flags_df.head())

print("=" * 60)
print("SKU MASTER DATASET")
display(sku_df.head())

print("=" * 60)
print("STORE DATASET")
display(store_df.head())

============================================================
CUSTOMER DATASET

,cust_id,age,gender,city,loyalty_segment,preferred_channel,registration_date
0,CUST00001,52,Female,Sukkur,Silver,Online,2021-01-01
1,CUST00002,41,Female,Karachi,Silver,Mobile App,2021-05-14
2,CUST00003,48,Female,Bahawalpur,Bronze,In-Store,2022-10-23
3,CUST00004,45,Male,Karachi,Silver,In-Store,2015-07-15
4,CUST00005,39,Female,Faisalabad,Bronze,In-Store,2024-01-02

============================================================
INVENTORY DATASET

,store_id,sku_id,stock_on_hand,reorder_point,safety_stock,last_restock_date
0,ST11,SKU02558,333,72,22,2025-06-23
1,ST21,SKU01031,236,67,14,2025-06-17
2,ST26,SKU02129,496,96,34,2025-07-10
3,ST19,SKU02907,109,34,13,2025-08-17
4,ST05,SKU01023,333,97,22,2025-07-12

============================================================
PROMOTIONS DATASET

,promo_id,promo_name,start_date,end_date,discount_pct,promo_type,target_type,target_value
0,PROMO001,Spring Discount Days,2024-07-28,2024-08-02,15.1,BOGO,Brand,NovaFresh
1,PROMO002,Summer Savings Event,2023-03-09,2023-03-21,7.0,Bundle Offer,All,All
2,PROMO003,Payday Discount Days,2025-04-30,2025-05-26,10.2,BOGO,Brand,ZestyCo
3,PROMO004,Super Sale,2025-06-07,2025-06-17,15.9,Clearance,SKU,SKU01108
4,PROMO005,Festive Discount Days,2024-03-23,2024-04-08,46.0,Bundle Offer,All,All

============================================================
SALES DATASET

,date,receipt_id,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct,promo_id
0,2025-04-02,RCPT00000001,ST16,SKU02498,CUST01410,1,2379.11,2379.11,In-Store,0.0,NaN
1,2025-04-02,RCPT00000001,ST16,SKU04596,CUST01410,3,335.55,1006.65,In-Store,0.0,NaN
2,2022-04-24,RCPT00000002,ST15,SKU00078,CUST00134,1,820.53,820.53,Online,0.0,NaN
3,2022-04-24,RCPT00000002,ST15,SKU00554,CUST00134,2,88.32,176.64,Online,0.0,NaN
4,2024-09-22,RCPT00000003,ST20,SKU03727,CUST08826,1,1660.93,1660.93,Online,0.0,NaN

============================================================
SKU INVENTORY FLAGS DATASET

,sku_id,flag,affected_stores,window_start,window_end,notes
0,SKU04321,STOCKOUT_RISK,ST22;ST26;ST23;ST15;ST12;ST28;ST01;ST27;ST08;S...,2025-11-06,2025-12-03,Top-selling SKU (by observed volume); injected...
1,SKU04596,STOCKOUT_RISK,ST12;ST09;ST21;ST23;ST07;ST24;ST01;ST28;ST14;S...,2025-10-25,2025-11-06,Top-selling SKU (by observed volume); injected...
2,SKU03727,STOCKOUT_RISK,ST19;ST14;ST28;ST29;ST02;ST07;ST17;ST08;ST05;ST16,2025-11-08,2025-11-29,Top-selling SKU (by observed volume); injected...
3,SKU04154,STOCKOUT_RISK,ST15;ST03;ST30;ST09;ST24;ST19;ST28;ST02;ST07;S...,2025-11-12,2025-11-26,Top-selling SKU (by observed volume); injected...
4,SKU00953,STOCKOUT_RISK,ST09;ST19;ST27;ST20;ST01;ST03;ST11;ST10;ST22;S...,2025-11-29,2025-12-25,Top-selling SKU (by observed volume); injected...

============================================================
SKU MASTER DATASET

,sku_id,sku_name,category,subcategory,unit_price,cost_price,brand
0,SKU00001,NutriPlus Cookware Large,Home & Kitchen,Cookware,813.41,619.77,NutriPlus
1,SKU00002,CrispKing Bread Family Pack,Dairy & Bakery,Bread,70.38,49.57,CrispKing
2,SKU00003,SoftTouch Notebooks 2L,Stationery & Office,Notebooks,151.28,83.67,SoftTouch
3,SKU00004,SunriseFoods Eggs Large,Dairy & Bakery,Eggs,233.64,156.32,SunriseFoods
4,SKU00005,SunriseFoods Pest Control Pack of 6,Home Care,Pest Control,138.50,83.46,SunriseFoods

============================================================
STORE DATASET

,store_id,store_name,city,store_type,opening_date
0,ST01,Quetta Convenience Store #01,Quetta,Convenience Store,2017-07-08
1,ST02,Islamabad Express Store #02,Islamabad,Express Store,2019-05-08
2,ST03,Sialkot Supermarket #03,Sialkot,Supermarket,2019-03-28
3,ST04,Multan Supermarket #04,Multan,Supermarket,2017-10-08
4,ST05,Karachi Supermarket #05,Karachi,Supermarket,2020-11-03

In [10]:
print("=" * 60)
print("CUSTOMER DATASET")
customer_df.info()

print("=" * 60)
print("INVENTORY DATASET")
inventory_df.info()

print("=" * 60)
print("PROMOTIONS DATASET")
promotions_df.info()

print("=" * 60)
print("SALES DATASET")
sales_df.info()

print("=" * 60)
print("SKU INVENTORY FLAGS DATASET")
sku_flags_df.info()

print("=" * 60)
print("SKU MASTER DATASET")
sku_df.info()

print("=" * 60)
print("STORE DATASET")
store_df.info()

============================================================
CUSTOMER DATASET
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cust_id            10000 non-null  str
 1   age                10000 non-null  int64
 2   gender             10000 non-null  str
 3   city               10000 non-null  str
 4   loyalty_segment    10000 non-null  str
 5   preferred_channel  10000 non-null  str
 6   registration_date  10000 non-null  str
dtypes: int64(1), str(6)
memory usage: 547.0 KB
============================================================
INVENTORY DATASET
<class 'pandas.DataFrame'>
RangeIndex: 26408 entries, 0 to 26407
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   store_id           26408 non-null  str
 1   sku_id             26408 non-null  str
 2   stock_on_hand      26408 non-null  int64
 3   reorder_point      26408 non-null  int64
 4   safety_stock       26408 non-null  int64
 5   last_restock_date  26408 non-null  str
dtypes: int64(3), str(3)
memory usage: 1.2 MB
============================================================
PROMOTIONS DATASET
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   promo_id      100 non-null    str
 1   promo_name    100 non-null    str
 2   start_date    100 non-null    str
 3   end_date      100 non-null    str
 4   discount_pct  100 non-null    float64
 5   promo_type    100 non-null    str
 6   target_type   100 non-null    str
 7   target_value  100 non-null    str
dtypes: float64(1), str(7)
memory usage: 6.4 KB
============================================================
SALES DATASET
<class 'pandas.DataFrame'>
RangeIndex: 9945511 entries, 0 to 9945510
Data columns (total 11 columns):
 #   Column        Dtype
---  ------        -----
 0   date          str
 1   receipt_id    str
 2   store_id      str
 3   sku_id        str
 4   customer_id   str
 5   quantity      int64
 6   unit_price    float64
 7   total_value   float64
 8   channel       str
 9   discount_pct  float64
 10  promo_id      str
dtypes: float64(3), int64(1), str(7)
memory usage: 834.7 MB
============================================================
SKU INVENTORY FLAGS DATASET
<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sku_id           600 non-null    str
 1   flag             600 non-null    str
 2   affected_stores  600 non-null    str
 3   window_start     200 non-null    str
 4   window_end       200 non-null    str
 5   notes            600 non-null    str
dtypes: str(6)
memory usage: 28.3 KB
============================================================
SKU MASTER DATASET
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku_id       5000 non-null   str
 1   sku_name     5000 non-null   str
 2   category     5000 non-null   str
 3   subcategory  5000 non-null   str
 4   unit_price   5000 non-null   float64
 5   cost_price   5000 non-null   float64
 6   brand        5000 non-null   str
dtypes: float64(2), str(5)
memory usage: 273.6 KB
============================================================
STORE DATASET
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      30 non-null     str
 1   store_name    30 non-null     str
 2   city          30 non-null     str
 3   store_type    30 non-null     str
 4   opening_date  30 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

In [11]:
print("=" * 60)
print("CUSTOMER DATASET")
print(customer_df.isnull().sum())

print("=" * 60)
print("INVENTORY DATASET")
print(inventory_df.isnull().sum())

print("=" * 60)
print("PROMOTIONS DATASET")
print(promotions_df.isnull().sum())

print("=" * 60)
print("SALES DATASET")
print(sales_df.isnull().sum())

print("=" * 60)
print("SKU INVENTORY FLAGS DATASET")
print(sku_flags_df.isnull().sum())

print("=" * 60)
print("SKU MASTER DATASET")
print(sku_df.isnull().sum())

print("=" * 60)
print("STORE DATASET")
print(store_df.isnull().sum())

============================================================
CUSTOMER DATASET
cust_id              0
age                  0
gender               0
city                 0
loyalty_segment      0
preferred_channel    0
registration_date    0
dtype: int64
============================================================
INVENTORY DATASET
store_id             0
sku_id               0
stock_on_hand        0
reorder_point        0
safety_stock         0
last_restock_date    0
dtype: int64
============================================================
PROMOTIONS DATASET
promo_id        0
promo_name      0
start_date      0
end_date        0
discount_pct    0
promo_type      0
target_type     0
target_value    0
dtype: int64
============================================================
SALES DATASET
date                  0
receipt_id            0
store_id              0
sku_id                0
customer_id           0
quantity              0
unit_price            0
total_value           0
channel               0
discount_pct          0
promo_id        7855345
dtype: int64
============================================================
SKU INVENTORY FLAGS DATASET
sku_id               0
flag                 0
affected_stores      0
window_start       400
window_end         400
notes                0
dtype: int64
============================================================
SKU MASTER DATASET
sku_id         0
sku_name       0
category       0
subcategory    0
unit_price     0
cost_price     0
brand          0
dtype: int64
============================================================
STORE DATASET
store_id        0
store_name      0
city            0
store_type      0
opening_date    0
dtype: int64

In [12]:
print("Customer:", customer_df.duplicated().sum())
print("Inventory:", inventory_df.duplicated().sum())
print("Promotions:", promotions_df.duplicated().sum())
print("Sales:", sales_df.duplicated().sum())
print("SKU Inventory Flags:", sku_flags_df.duplicated().sum())
print("SKU Master:", sku_df.duplicated().sum())
print("Store:", store_df.duplicated().sum())

Customer: 0
Inventory: 0
Promotions: 0
Sales: 12897
SKU Inventory Flags: 0
SKU Master: 0
Store: 0

In [13]:
print("=" * 60)
print("CUSTOMER DATASET")
display(customer_df.describe(include="all"))

print("=" * 60)
print("INVENTORY DATASET")
display(inventory_df.describe(include="all"))

print("=" * 60)
print("PROMOTIONS DATASET")
display(promotions_df.describe(include="all"))

print("=" * 60)
print("SALES DATASET")
display(sales_df.describe(include="all"))

print("=" * 60)
print("SKU INVENTORY FLAGS DATASET")
display(sku_flags_df.describe(include="all"))

print("=" * 60)
print("SKU MASTER DATASET")
display(sku_df.describe(include="all"))

print("=" * 60)
print("STORE DATASET")
display(store_df.describe(include="all"))

============================================================
CUSTOMER DATASET

,cust_id,age,gender,city,loyalty_segment,preferred_channel,registration_date
count,10000,10000.000000,10000,10000,10000,10000,10000
unique,10000,NaN,3,15,4,3,3661
top,CUST00001,NaN,Female,Karachi,Bronze,In-Store,2025-02-02
freq,1,NaN,4930,1577,3969,5512,10
mean,NaN,37.702900,NaN,NaN,NaN,NaN,NaN
std,NaN,12.190106,NaN,NaN,NaN,NaN,NaN
min,NaN,18.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,29.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,37.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,46.000000,NaN,NaN,NaN,NaN,NaN
max,NaN,80.000000,NaN,NaN,NaN,NaN,NaN

============================================================
INVENTORY DATASET

,store_id,sku_id,stock_on_hand,reorder_point,safety_stock,last_restock_date
count,26408,26408,26408.000000,26408.000000,26408.000000,26408
unique,30,4495,NaN,NaN,NaN,221
top,ST03,SKU01031,NaN,NaN,NaN,2025-08-31
freq,918,30,NaN,NaN,NaN,211
mean,NaN,NaN,166.195812,59.983301,20.951719,NaN
std,NaN,NaN,142.238780,23.389128,9.873781,NaN
min,NaN,NaN,0.000000,20.000000,4.000000,NaN
25%,NaN,NaN,40.000000,40.000000,13.000000,NaN
50%,NaN,NaN,140.000000,60.000000,20.000000,NaN
75%,NaN,NaN,264.000000,80.000000,28.000000,NaN
max,NaN,NaN,598.000000,100.000000,50.000000,NaN

============================================================
PROMOTIONS DATASET

,promo_id,promo_name,start_date,end_date,discount_pct,promo_type,target_type,target_value
count,100,100,100,100,100.000000,100,100,100
unique,100,72,96,97,NaN,5,4,49
top,PROMO001,Payday Discount Days,2024-10-22,2025-05-23,NaN,Bundle Offer,Category,All
freq,1,5,2,2,NaN,23,38,19
mean,NaN,NaN,NaN,NaN,27.580000,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,14.134348,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,15.400000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,25.400000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,42.575000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,49.800000,NaN,NaN,NaN

============================================================
SALES DATASET

,date,receipt_id,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct,promo_id
count,9945511,9945511,9945511,9945511,9945511,9.945511e+06,9.945511e+06,9.945511e+06,9945511,9.945511e+06,2090166
unique,1461,5167864,30,5000,10000,NaN,NaN,NaN,3,NaN,96
top,2025-12-29,RCPT00000038,ST29,SKU04321,CUST06744,NaN,NaN,NaN,In-Store,NaN,PROMO045
freq,9856,5,472578,630147,2303,NaN,NaN,NaN,5496812,NaN,185809
mean,NaN,NaN,NaN,NaN,NaN,1.880336e+00,6.215749e+02,1.094512e+03,NaN,6.289965e+00,NaN
std,NaN,NaN,NaN,NaN,NaN,1.089063e+00,6.751952e+02,1.536814e+03,NaN,1.383267e+01,NaN
min,NaN,NaN,NaN,NaN,NaN,1.000000e+00,2.441000e+01,1.225000e+01,NaN,0.000000e+00,NaN
25%,NaN,NaN,NaN,NaN,NaN,1.000000e+00,1.734300e+02,2.351700e+02,NaN,0.000000e+00,NaN
50%,NaN,NaN,NaN,NaN,NaN,2.000000e+00,3.367200e+02,5.432000e+02,NaN,0.000000e+00,NaN
75%,NaN,NaN,NaN,NaN,NaN,3.000000e+00,9.256700e+02,1.277610e+03,NaN,0.000000e+00,NaN
max,NaN,NaN,NaN,NaN,NaN,5.000000e+00,4.755470e+03,2.377735e+04,NaN,4.980000e+01,NaN

============================================================
SKU INVENTORY FLAGS DATASET

,sku_id,flag,affected_stores,window_start,window_end,notes
count,600,600,600,200,200,600
unique,600,2,600,60,62,2
top,SKU04321,SLOW_MOVER,ST22;ST26;ST23;ST15;ST12;ST28;ST01;ST27;ST08;S...,2025-10-21,2025-12-28,Bottom-selling SKU (by observed volume); injec...
freq,1,400,1,7,7,400

============================================================
SKU MASTER DATASET

,sku_id,sku_name,category,subcategory,unit_price,cost_price,brand
count,5000,5000,5000,5000,5000.000000,5000.000000,5000
unique,5000,4458,12,53,NaN,NaN,30
top,SKU00001,CityFresh Cheese Pack of 6,Stationery & Office,Writing Instruments,NaN,NaN,CleanWave
freq,1,3,459,164,NaN,NaN,193
mean,NaN,NaN,NaN,NaN,619.191672,417.040736,NaN
std,NaN,NaN,NaN,NaN,708.009319,480.347009,NaN
min,NaN,NaN,NaN,NaN,24.410000,16.750000,NaN
25%,NaN,NaN,NaN,NaN,160.555000,108.825000,NaN
50%,NaN,NaN,NaN,NaN,318.745000,214.670000,NaN
75%,NaN,NaN,NaN,NaN,788.715000,530.027500,NaN
max,NaN,NaN,NaN,NaN,4755.470000,3398.160000,NaN

============================================================
STORE DATASET

,store_id,store_name,city,store_type,opening_date
count,30,30,30,30,30
unique,30,30,12,4,30
top,ST01,Quetta Convenience Store #01,Karachi,Convenience Store,2017-07-08
freq,1,1,5,11,1

In [14]:
# Convert date columns to datetime format

customer_df["registration_date"] = pd.to_datetime(customer_df["registration_date"])

inventory_df["last_restock_date"] = pd.to_datetime(inventory_df["last_restock_date"])

promotions_df["start_date"] = pd.to_datetime(promotions_df["start_date"])
promotions_df["end_date"] = pd.to_datetime(promotions_df["end_date"])

sales_df["date"] = pd.to_datetime(sales_df["date"])

store_df["opening_date"] = pd.to_datetime(store_df["opening_date"])

print("Date conversion completed successfully.")

Date conversion completed successfully.

In [15]:
# Save cleaned datasets

customer_df.to_csv("../data/processed/customer_master_clean.csv", index=False)

inventory_df.to_csv("../data/processed/inventory_snapshot_clean.csv", index=False)

promotions_df.to_csv("../data/processed/promotions_clean.csv", index=False)

sales_df.to_csv("../data/processed/sales_transactions_clean.csv", index=False)

sku_flags_df.to_csv("../data/processed/sku_inventory_flags_clean.csv", index=False)

sku_df.to_csv("../data/processed/sku_master_clean.csv", index=False)

store_df.to_csv("../data/processed/store_master_clean.csv", index=False)

print("All cleaned datasets saved successfully in data/processed/")

All cleaned datasets saved successfully in data/processed/